name: DEPLOY
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node modules
        run: npm install
      - name: create .env
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "NOTION_API_TOKEN=${{ secrets.NOTION_API_TOKEN }}" >> .env
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude-from="rsync-exclude-list.txt"
          path: ./
          remote_path: /home/wagumi/apps/members-db-updater
          remote_host: wagumi-prod-jpe-001.japaneast.cloudapp.azure.com
          remote_user: wagumi
          remote_port: 57822
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: make id_rsa
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> .id_rsa
          chmod 600 .id_rsa
      - name: ssh connert and pm2 run
        run: |
          ssh -t -t -o "StrictHostKeyChecking no" -i .id_rsa wagumi-prod-jpe-001.japaneast.cloudapp.azure.com "
          cd /home/wagumi/apps/members-db-updater
          npm install
          pm2 start main.js --cron-restart="10 0 * * *â€
          "